### PR TITLE
Alana starting on UI

### PR DESCRIPTION
**Pull request by prettyalana**

### CODE REVIEW

**Review by ajmompr — CHANGES_REQUESTED** [review]
Hi Alana! Great job creating your starting-on-ui branch. However, can you edit this pull request to reflect a review from your alana-starting-on-ui branch to your alana-photogram-industrial-2 branch? Typically, when creating a feature branch you would always merge into main. However, for this exercise we would like you all to create branches from the previous feature branch. Please let me know if you have any questions!

**Review by ajmompr — APPROVED** [review]
Hi Alana! Thank you for updating your pull request; good job creating your sample data!

**Review by WCW789 — APPROVED** [review]
Hi Alana, looks great!

**Review by andrewp8 — APPROVED** [review]
Hi Alana, great job!

**Pull request merged**
